version: '3.7'

services:
  registry:
    image: registry:2.7.0
    restart: always
    # ports:
    #   - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry-data:/var/lib/registry
      - registry-auth:/auth
    networks:
      - traefik_default
      - default
    labels:
      - "traefik.port=5000"
      - "traefik.enable=true"
      # - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.registry.rule=Host(`${APP_FQDN:-localhost}`)"
      - "traefik.http.routers.registry.entrypoints=web"
      - "traefik.http.routers.registry-tls.rule=Host(`${APP_FQDN:-localhost}`)"
      - "traefik.http.routers.registry-tls.entrypoints=websecure"
      - "traefik.http.routers.registry-tls.tls.certresolver=default"

volumes:
  registry-auth:
  registry-data:

networks:
  traefik_default:
    external: true
